### ISSUE TITLE
Investigate free audio player options

### ISSUE THREAD

**Issue by nathanbedford** [nathan-bedford-software/audio-message-player#3]
Instead of writing the audio player part from scratch, we can use a good existing free one. 

Here's one option:
http://jplayer.org/latest/demos/

Feel free to investigate and find other ones.

**Comment by NMaass** [comment]
That's the best free one I've seen. Do we want it to look more like the video playlist demo than the mockup?

**Comment by nathanbedford** [comment]
Cool, we can go with jplayer then.  While the video playlist is cool, in this case I'd like to create the playlist ourselves so we have a chance to customize it to our needs.

Options I'm liking:
http://jplayer.org/latest/demo-01/
http://jplayer.org/latest/demo-05/
